### PR TITLE
Add Puma clustered mode support

### LINKED ISSUE #16: Can't get this gem working?
I tried this gem on a few of my projects that use HAML files, doesn't seem to be working. Did i miss something not in the documentation?
Installed the gem and then started the server. 
It shows this but doesn't do anything.
```
Watching: /Users/jake/Repos/Nurture
  (?-mix:app\/views\/.+\.(erb|haml|slim)$) => on_change
  (?-mix:(app|vendor)\/(assets|javascript)\/\w+\/(.+\.(css|js|html|png|jpg|ts|jsx)).*) => always
```
https://www.loom.com/share/a34dd1367fc849c8a6b2c4c39284cf13

### PR DESCRIPTION
**Pull request by manastyretskyi**
There are couple of major internal changes made in this PR:
- Added unix sockets for communication between processes. Fixes #16.
- Removed deprecated code.
- Used separately mounted server instead of `middleware` for `rails_live_reload` requests.

### CODE REVIEW

**Comment by manastyretskyi** [comment]
Hey @jacobperia, it would be great if you could try this branch before it is merged, so that we can confirm that it works properly.
Other's help with testing this would be appreciated as well. So far it seems to be working fine, but it would be great if other people tried this.

**Comment by jacobperia** [comment]
> Hey @jacobperia, it would be great if you could try this branch before it is merged, so that we can confirm that it works properly. Other's help with testing this would be appreciated as well. So far it seems to be working fine, but it would be great if other people tried this.

This worked perfectly. Great job :)

**Review by jacobperia — APPROVED** [review]

**Comment by jacobperia** [comment]
@igorkasyanchuk has the gem been updated globally to now work?

**Comment by manastyretskyi** [comment]
Not yet, I think I will release new version later today.

**Comment by manastyretskyi** [comment]
@jacobperia I just released new version, you can get it from RubyGems now.
https://github.com/railsjazz/rails_live_reload/releases/tag/v0.3.0

**Pull request merged**
